/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.io.IOException;
import java.nio.file.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class GestionArchivos extends javax.swing.JInternalFrame {
   File File ;
   String Path;
   DefaultListModel modelo = new DefaultListModel();
    /**
     * Creates new form GestionArchivos
     */
    public GestionArchivos() {
        initComponents();
        //ListaDirectorios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExaminar = new javax.swing.JButton();
        txtArchivo = new javax.swing.JTextField();
        btnCambiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDirectorios = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaFicheros = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDirectorio = new javax.swing.JLabel();
        btnManual = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestión de Archivos ");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel4.setText("Hospital Ángeles Tampico");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setText("Departamento de Ingeniería Biomédica");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Ing. Victor Hugo Hernández Hernández");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/IngBiomedica.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/Imagenes/HAngeles.jpg"))); // NOI18N

        btnExaminar.setText("Examinar");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });

        btnCambiar.setText("Mover");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        listaDirectorios.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Limpieza y Desinfeccion", "Verificacion Areas", "Verificacion Equipos", "Manuales de Usuario", "Manuales de Servicio", "Fichas Tecnicas" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaDirectorios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaDirectorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDirectoriosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaDirectorios);

        listaFicheros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFicherosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaFicheros);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Directorios:");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Ficheros que contiene el directorio ");

        lblDirectorio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnManual.setText("Gestión Manual");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExaminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManual)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel5))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6))
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExaminar)
                    .addComponent(btnCambiar)
                    .addComponent(btnManual))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(lblDirectorio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed
      JFileChooser dlg = new JFileChooser();
      //dlg.set
      int option = dlg.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
        String file = dlg.getSelectedFile().getName();
        File = new File(file);
        Path = dlg.getSelectedFile().getAbsolutePath();
        txtArchivo.setText(file);
        
        
        }
    }//GEN-LAST:event_btnExaminarActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
    Path DESTINO = Paths.get("src\\hospital\\Documentos\\"+listaDirectorios.getSelectedValue().toString()+"\\"+File.getName());
       
//       Path DESTINO = Paths.get("C:\\Users\\Usuario\\Desktop\\Manuales\\"+File.getName());
       Path ORIGEN = Paths.get(Path);
       JOptionPane.showMessageDialog(this,"Cambio realizado de manera exitosa");
       System.out.println("D: "+ DESTINO);
        
        System.out.println("O : " +ORIGEN);
       try {
           
           Files.move(ORIGEN , DESTINO ,StandardCopyOption.REPLACE_EXISTING);
       } catch (IOException ex) {
           Logger.getLogger(GestionArchivos.class.getName()).log(Level.SEVERE, null, ex);
       }
    
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void listaDirectoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDirectoriosMouseClicked
            Point point = evt.getPoint();
   if (evt.getClickCount() == 2) {
          String Carpeta = listaDirectorios.getSelectedValue().toString();
           listaFicheros.removeAll();
           lblDirectorio.setText(Carpeta);
          CargarArchivos(Carpeta);}
    }//GEN-LAST:event_listaDirectoriosMouseClicked

    private void listaFicherosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFicherosMouseClicked
     Point point = evt.getPoint();
   if (evt.getClickCount() == 2) {
          String Archivo = listaFicheros.getSelectedValue().toString();
          txtArchivo.setText(Archivo);
   }
    }//GEN-LAST:event_listaFicherosMouseClicked

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
      Runtime r = Runtime.getRuntime();
		Process p = null;

		try {
			p = r.exec("explorer.exe src\\hospital\\Documentos\\");
		} catch (Exception e) {
			System.out.println("Error al ejecutar");
		}
    }//GEN-LAST:event_btnManualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnManual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDirectorio;
    private javax.swing.JList listaDirectorios;
    private javax.swing.JList listaFicheros;
    private javax.swing.JTextField txtArchivo;
    // End of variables declaration//GEN-END:variables

    private void ListaDirectorios() {
   
         String sDirectorio = "src\\hospital\\";
        File f = new File(sDirectorio);
        if (f.exists()){ 
     File[] ficheros = f.listFiles();
   for (int x=0;x<ficheros.length;x++){
         modelo.addElement(ficheros[x].getName().substring(0, ficheros[x].getName().lastIndexOf(".")));
  }
}else{ //Directorio no existe }
    JOptionPane.showMessageDialog(this.getParent(), "La carpeta especificada no existe");
    }
     listaDirectorios.setModel(modelo);
    
    }

    private void CargarArchivos(String Carpeta) {
       
       
     modelo.removeAllElements();
        String sDirectorio = "src\\hospital\\Documentos\\"+Carpeta+"\\";
        File f = new File(sDirectorio);
        if (f.exists()){ 
     File[] ficheros = f.listFiles();
   for (int x=0;x<ficheros.length;x++){
         modelo.addElement(ficheros[x].getName().substring(0, ficheros[x].getName().lastIndexOf(".")));
  }
}else{ //Directorio no existe }
    JOptionPane.showMessageDialog(this.getParent(), "La carpeta especificada no existe");
    }
     listaFicheros.setModel(modelo);
     }
}
